[package]
name = "reportlinkfix"
version = "0.1.2"
edition = "2021"
description = "Authentication workaround for N-Central Report Manager. Takes the link that N-Central creates for Report Manager and outputs a working link"